apiVersion: v1
kind: ServiceAccount
metadata:
  name: doc-generator-sa
  namespace: gxp-doc
  labels:
    compliance: gxp
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::583299526477:role/gxp-doc-generator-role
